# Generated by Django 5.1.4 on 2025-01-13 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_coin_code_alter_coin_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('FaceBook', 'FaceBook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], default=datetime.datetime(2025, 1, 13, 14, 33, 14, 737685, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
