# Generated by Django 5.1.4 on 2025-01-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_video_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='currency_type',
            new_name='currencytype',
        ),
    ]
