# Generated by Django 5.1.4 on 2025-01-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_currency_type_exchange_currencytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='coin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
