# Generated by Django 5.1.4 on 2025-01-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_exchange_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='coin',
        ),
    ]
