# Generated by Django 5.1.4 on 2025-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=6000, unique=True),
        ),
    ]
