# Generated by Django 5.1.4 on 2025-01-19 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.CreateModel(
            name='CoinMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_value', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('miner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mined_coins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatChannel',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
