# Generated by Django 5.1.4 on 2025-01-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_chatmessage_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
