# Generated by Django 5.1.4 on 2025-01-21 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_usedcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True)),
                ('daily_cipher', models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True)),
                ('daily_combo', models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
