# Generated by Django 5.1.4 on 2025-01-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messagesreceiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
