# Generated by Django 5.1.4 on 2025-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(max_length=15),
        ),
    ]
