# Generated by Django 5.1.4 on 2025-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_onlineshop_customerpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshop',
            name='stock_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
