# Generated by Django 5.1.4 on 2025-02-01 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_alter_onlineshop_stock_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('EUR', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('JPY', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('GBP', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('AUD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('CAD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('CHF', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('CNY', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('HKD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('NZD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('INR', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('BRL', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('RUB', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('ZAR', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('AED', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('SAR', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('MXN', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('SHD', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('KRW', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('ETB', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('KES', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('TZS', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('GHS', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('UGX', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('XAF', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('XOF', models.IntegerField(blank=True, default=0, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
