# Generated by Django 5.1.4 on 2025-02-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_alter_cashrate_aed_alter_cashrate_aud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=''),
        ),
    ]
