# Generated by Django 5.1.4 on 2025-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_customuser_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
