# Generated by Django 5.1.4 on 2025-02-09 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_customuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
