# Generated by Django 5.1.4 on 2025-02-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_customerpurchase_timestamp_onlineshop_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_one', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_two', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_three', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_four', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_five', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateTimeField()),
                ('accomplishment_value', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
