# Generated by Django 5.1.4 on 2025-02-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_daily_combo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Combo',
            new_name='DailyCombo',
        ),
    ]
