# Generated by Django 5.1.4 on 2025-02-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_dailycombo_timestamp_dailycomboclain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyComboClain',
            new_name='DailyComboClaim',
        ),
    ]
