# Generated by Django 5.1.4 on 2025-01-14 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0024_alter_chatchannel_participants_and_more'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('bank_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Account.publish')),
            ],
        ),
    ]
