# Generated by Django 5.1.4 on 2025-01-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0026_publish_no_of_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
