# Generated by Django 5.1.4 on 2025-01-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0027_paymentinfo_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinvest',
            name='no_of_photos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='CommentInvestPhoto',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image_url', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentphotos', to='Account.publish')),
            ],
        ),
    ]
