# Generated by Django 5.1.4 on 2025-01-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0028_commentinvest_no_of_photos_commentinvestphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinvestphoto',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentinvestphotos', to='Account.invest'),
        ),
        migrations.CreateModel(
            name='CommentPublishPhoto',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image_url', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpublishphotos', to='Account.publish')),
            ],
        ),
    ]
