# Generated by Django 5.1.4 on 2025-01-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0029_alter_commentinvestphoto_parent_commentpublishphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpublish',
            name='no_of_photos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
