# Generated by Django 5.1.4 on 2025-01-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0030_commentpublish_no_of_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinvestphoto',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentinvestphotos', to='Account.commentinvest'),
        ),
        migrations.AlterField(
            model_name='commentpublishphoto',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpublishphotos', to='Account.commentpublish'),
        ),
    ]
