# Generated by Django 5.1.4 on 2025-01-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0031_alter_commentinvestphoto_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentinvest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='commentpublish',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='commentinvest',
            name='no_of_photos',
        ),
        migrations.RemoveField(
            model_name='commentpublish',
            name='no_of_photos',
        ),
        migrations.AddField(
            model_name='commentinvest',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Account.commentinvest'),
        ),
        migrations.AddField(
            model_name='commentinvest',
            name='photos',
            field=models.FileField(blank=True, default=0, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='commentpublish',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Account.commentpublish'),
        ),
        migrations.AddField(
            model_name='commentpublish',
            name='photos',
            field=models.FileField(blank=True, default=0, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='commentpublish',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Account.publish'),
        ),
    ]
