# Generated by Django 5.1.4 on 2025-01-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0032_alter_commentinvest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpublishphoto',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CommentInvestPhoto',
        ),
        migrations.DeleteModel(
            name='CommentPublishPhoto',
        ),
    ]
