# Generated by Django 5.1.4 on 2025-01-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0033_remove_commentpublishphoto_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinvest',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentinvest', to='Account.invest'),
        ),
        migrations.AlterField(
            model_name='commentinvest',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliesinvest', to='Account.commentinvest'),
        ),
        migrations.AlterField(
            model_name='commentpublish',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentspublish', to='Account.publish'),
        ),
        migrations.AlterField(
            model_name='commentpublish',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliespublish', to='Account.commentpublish'),
        ),
    ]
